---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    types:
      - opened
      - synchronize

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Print linting errors
        run: grep "^\/github\/workspace\/" super-linter.log
      - name: Set SUPER_LINTER_OUTPUT variable
        run: SUPER_LINTER_OUTPUT=$(grep "^\/github\/workspace\/" test.txt | tr '\n' '\1')
      ########################
      # Comment output on PR #
      ########################
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Please address the following issues:**
            ${echo "$SUPER_LINTER_OUTPUT" | tr '\1' '\n'}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
